### ISSUE TITLE
GetRegionFromTemplate() should get region from Template Metadata

### ISSUE THREAD

**Issue by MrSnowflake** [bkoopman/tri#17]
It's not clear to me why `Sdl.Web.Tridion.Common.TemplateBase.GetRegionFromTemplate()` gets its parent region from the template title. 

The template's region is already specified on its metadata . Configuration should not be part of a template's title. It belongs in the metadata schema (that's what it's for).

**Comment by willprice76** [comment]
Good point. The web app (Sdl.Web.DD4T.Mapping.DD4TModelBuilder.GetRegionFromComponentPresentation) has different logic:
1. Check the metadata of the CT
2. If none, check the title of the CT to see whats in the square brackets
3. If no square brackets default to "Main"
The TBB should do the same.

**Comment by bkoopman** [comment]
Fair point indeed, we do have other cases where we depend on the Template Title, and that is for Dynamic Component Presentations, since unfortunately the metadata of a Component Template is not published to the Broker right now.
But that doesn;t change the fact that GetRegionFromTemplate should simply follow the same rules as the web application does as mentioned by Will.

**Comment by bkoopman** [comment]
fixed in DXA 1.1 https://community.sdl.com/developers/tridion_developer/m/mediagallery/852
