### ISSUE TITLE
Wrong Navigation/Breadcrumb if Capital letters are used in SG Directory

### ISSUE THREAD

**Issue by lagostinelli** [bkoopman/tri#18]
If any capital letter is used in the Directory name of a first level Structure Group, the left navigation within that section doesn’t work properly: it displays the first level navigation (like the Top one) instead if the pages at the second level and also the Breadcrumb doesn’t work.

![wrong nav](https://cloud.githubusercontent.com/assets/13311053/8645536/7c10e012-2948-11e5-98f7-fcd1ace726ba.jpg)

I tried removing Capital letters and it goes back to work properly. 
I am not sure if there is a specific reason for this but I think it should work also with capital letters.

**Comment by willprice76** [comment]
I think this is due to the request URL not being case-insensitive compared, to determine the context structure group. Try changing this line 

https://github.com/bkoopman/tri/blob/master/web-application/Sdl.Web.Mvc/ContentProvider/NavigationBuilder.cs#L22

as follows

var newParent = parent.Items.FirstOrDefault(i => i.Type == "StructureGroup" && requestUrl.StartsWith(i.Url.ToLower(),StringComparison.InvariantCultureIgnoreCase));

**Comment by bkoopman** [comment]
fixed in DXA 1.1 https://community.sdl.com/developers/tridion_developer/m/mediagallery/852
